### ISSUE TITLE
[Potential Bug]: Station mule and seller priority

### ISSUE THREAD

**Issue by Silencer** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#123] opened 2021-05-07 20:34 UTC
I have issue with station mule and seller priority

**Steps to reproduce the behaviour:**
So I have next one configuration:
1) Gas Factory which produce two type of wares:  Graphene and Superfluid Coolant
2) Warehouse, just trade station with big storage, which buys Graphene and Superfluid Coolant
I have one station mule that was assigned to this station and warehouse as target station, I check seller priority only so from behavior description it should taking wares that factory has at most, but it's take always only one ware Superfluid Coolant.

I have in factory storage next wares (from logical view):
  Superfluid Coolant - 4463 from 18545
  Graphene - 37403 from 37403 (at max storage capacity) 
In the warehouse I have (from logical view):
  Superfluid Coolant: 2347 from 5937
  Graphene: 73 wares from 5277

When I manually click on mule trade with my factory I see:
Ware | Sell offer 
-------| ------------
Graphene | 34,515
Superfluid Coolant | 2,838

When I manually click on trade with warehouse I see:
Ware | Sell offer | Buy offer
------|-----------|------------
Graphene | 79 |  2,310
Superfluid Coolant | 2,247 | 1,965

My mule  (Buffalo - L with storage 26 000) always take Superfluid Coolant = 1625 wares
May be I'm wrong but I think that it compare by total delivery amount of wares, because in case of Graphene it will be = 1444 wares

**Expected Behaviour**
According to **seller priority** it should take Graphene because it's a ware with maximum amount.

**Version Info (please complete the following information):**
 - X4 Foundations : v4.0 (434806) 
 - Mules Extended Mod : 633
 - I downloaded the mod from: Steam Workshop

**Comment by bhayden53** [comment] 2021-05-08 01:13
You shouldn't need to use the seller priority option; in fact in general I would not suggest it simply because I'm less confident in exactly how it works (not code that we wrote, we inherited it). I know the mule will do it's job fine without it. 

Some questions:
- Can you post the exact mule settings that are checked?
- what is the budget on the warehouse compared to the expected budget?
- on either the factory or the warehouse, have you done any manual changes to the wares in logical overview? 

That said, you may be right that it's sorting by volume when the "seller priority" option is checked:
https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/blob/21b2a6725b847f3fcf027e7b5f3dd110ed2f360f/aiscripts/station_mule.xml#L278

Despite the name and description, I think what it's doing is prioritizing the largest trade that the target wants to buy; not the largest amount of storage on the source station. It's hard to know off the top of my head exactly what "volume" means in this line, but it may not be behaving as intended.

I have an idea of how to fix it so that it sorts by a better value, but for the time being, if you simply uncheck seller priority, I think you ought to be able to get some graphene to go through. Alternatively, you could set a supply mule on the warehouse, locked to graphene only, and he'll run out to your factory and start bringing it back.

**Comment by bhayden53** [comment] 2021-05-08 02:20
pretty sure that sort_trades call was the problem; I have a fix put together already, going to group it up with a supply mule change as well.

**Comment by bhayden53** [comment] 2021-05-08 02:52
addressed in https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/pull/124

**Comment by Silencer** [comment] 2021-05-08 06:35
Thank you for your fast response and time, I take station_mule.xml from you patch and replace mine, to test this fix, this is debug output:
```
starting log file
sourceStation: [MG1] Eighteen Billion - Mine Gas Station
targetStation: [WH1] Second Contact II - Warehouse
----- main station mule routine
  found 19 needs and 3 supplies
  sourceStation priority setting needs to innerList and supplies to outerList sorted by stocklevel descending
    Graphene 673254 1
    Superfluid Coolant 71408 0.240658
    Hydrogen 116904 0.19484
-----crazy insane logic block checking
  ware Graphene
  cargoHauled 1444
  affordableAmount 1444
  targetOfferedAmount 5198
  tradeAmount 1444
  allowLowVol 0
  targetIsResource 0
  targetIsProduct 0
  targetIsWare 1
  sourceIsResource 0
  sourceIsProduct 1
  sourceIsWare 0
  targetIsIntermediate 0
  targetStockLevel 0.413872
  continue 0
  this.ship.cargo.{$supplyTarget.ware}.max / 1.25 1155.2
  supplytargetDesiredAmount 5198
  supplytargetAmount 2184
  supplyTarget owner class station
  $supplyTarget.owner.cargo.{$supplyTarget.ware}.target 5277
moving 1444 Graphene from [MG1] Eighteen Billion - Mine Gas Station to [WH1] Second Contact II - Warehouse
-----after main trade logic block
  loop: 1
  resetting supplies list
  resetting needs list
-----after main trade logic block
  loop: 2
  resetting supplies list
  resetting needs list
-----after main trade logic block
  loop: 3
  resetting needs list
-----after main trade logic block
  loop: 4
  resetting needs list
```
So as you can see, now it's taken Graphene as expected, thanks!

**Closed as completed** 2022-03-22 14:15 UTC
Labels: Bug
