### ISSUE TITLE
Trade rules on a warehouse: travel mule and supply mule conflicts

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#78] opened 2020-06-07 17:53 UTC
A warehouse/trade station presents a little bit of a problem for the travel and supply mules. You want to be able to assign supply mules to the warehouse, then have travel mules taking stuff out and selling it. However, you can't really restrict the supply mules from buying from the AI with trade rules, because then the travel mule won't be able to sell. And you can't just disallow the supply mule from buying from the AI, because then the AI can still trade at the station.

It's a bit hard to solve because trade rules don't really provide the ability to distinguish between incoming and outgoing trades. You'd need basically two separate lists. It's already confusing enough with blacklists and trade rules and inverting the trade rules with the UI button. 

And I am strongly against adding faction checklists to the params for any of the mules. It's not a design path I want to go down when we already have blacklists and trade rules in the game. Ship specific blacklists are not something I think we should try to manage. 

One option may be to add a param to travel mule to ignore trade rules. The player would still be able to limit the factions the mule will sell to by using blacklists. The the trade rules could be setup so that supply mules only bought from the player, and no AI could trade at the warehouse. This might be the best option I was able to think of in the ~30 minutes I thought about it.

**Comment by Misunderstood-Wookiee** [comment] 2020-06-08 00:51
Sooo,
Just tell one of the mules to ignore the global rule or setup two different global rules. You can tell individual ships already to use a different global rule or ignore them.

For instance I have a supply mule but I also have a faction trade ban rule, by default these are set on every ship by the game, you go into the individual orders of a ship and tell it to ignore the global or choose a different global rule set.

Also if you make a global rule and not tick anything to deny it won't get set to every ship by default but the rule will apply if you assign the global to a ship at the individual Level. 


I use a warehouse/trade on my save already and it gets wares from two of my stations and the AI can buy and sell.

I also use trade bans to deny certain factions. I don't really understand what the issue is if the complain is about having the AI be able to do a thing on your trade warehouse but also trade ban AI that seems like you want to circumvent the thing you asked for with a trade ban.

Trade bans don't have to stop your ships from trading just the AI. I'm happy to go test an exact setup later using my stations I have already.

**Comment by bhayden53** [comment] 2020-06-08 01:31
Is the faction trade ban that you're talking about a trade rule, or a blacklist? I didn't think you could manually tell a ship to ignore a station's trade rule.

What I would say is that this doesn't help the players who use civ fleets, because I don't think civ fleets copies over the blacklist setting. That's probably buried in the lua and not available from the AIScript, if I had to guess. 

My solution to this, with the current mules, would be to have a player-only warehouse if I really wanted a warehouse with no AI trading. Then I'd keep a separate station setup in a different sector from all of my production to use as my trade station. But, you know, everyone is different.

But just to clarify, the user wants a warehouse where:
- the AI cannot trade at all
- supply and travel mule are unrestricted.  

This seems like a reasonable thing to me, and I don't think it's possible with 6.1.0 and 3.2. But I haven't gone in and actually tried to make it work.

**Comment by Misunderstood-Wookiee** [comment] 2020-06-08 07:06
I don't think this true, sounds more like the player fault to me, more detail explained in my reply to issue https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/79#issuecomment-640409447 on how the blacklist and trade bans are flexible enough to allow for both situations you just have to set them up with the intention of purpose (are they going to be defaults yes/no if no then you need to assign them to ships manually and stations manually e.t.c.

You have the control to setup these bans on a per ware basis and per ship basis and even per station basis so I don't understand the OP this to me looks a self-made conflict.

**Comment by bhayden53** [comment] 2020-06-08 15:09
One solution that Wookie came up with that I kind of like:
- set up the trade rule to ignore all AI
- on the logical overview of the warehouse, override all of the "sell" trade rules. 

This will allow the travel mule to work, while blocking any AI supply of the warehouse. It will allow the AI to come to the station, but only to buy things from you.

IMO, this is sufficient of a solution without adding more params.

**Comment by Misunderstood-Wookiee** [comment] 2020-06-19 07:36
Will leave move this ticket to won't be fixed and question tag, and close it for now.
may get evaluated again in future. _Likely whenever we get around to the parameter re-factor._

**Closed as completed by Misunderstood-Wookiee** 2020-06-19 07:36 UTC
Labels: Question, Won't Be FIxed
